---
- name: add salt repo and gpg key
  hosts: all
  become: True

  tasks:
    - name: Copy salt APT repo .sources file
      ansible.builtin.copy:
        src: salt.sources
        dest: /etc/apt/sources.list.d/salt.sources
        owner: root
        group: root
        mode: 0644
    - name: Download salt archive-keyring pgp file
      ansible.builtin.get_url:
        url: https://packages.broadcom.com/artifactory/api/security/keypair/SaltProjectKey/public
        dest: /etc/apt/keyrings/salt-archive-keyring.pgp
        owner: root
        group: root
        mode: 0644
    - name: Create APT pin file for salt-3006.x LTS versions
      ansible.builtin.copy:
        content: |
          Package: salt-*
          Pin: version 3006.*
          Pin-Priority: 1001
        dest: /etc/apt/preferences.d/salt-pin-1001
